### ISSUE TITLE
Feedstock conversion from staged-recipes failing

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/status#116]
Feedstock conversion is currently failing with a permissions error from the Travis CI API. We're in contact with Travis's support and will report back here when more is known.

**Comment by beckermr** [comment]
We’ve tried several strategies to mitigate the error but have not had success. We’ll update with more details as we have them.

**Comment by beckermr** [comment]
This was an issue with Travis and deprecated GitHub auth. It appears to be fixed.
