### ISSUE TITLE
No CI checks for PRs on feedstocks

### ISSUE THREAD

**Issue by tomasvanpottelbergh** [conda-forge/status#117]
Since this morning the CI runs don't appear in the checks of PRs on feedstocks. This is affecting all feedstocks I have looked at.

See https://github.com/conda-forge/folly-feedstock/pull/1 for an example.

The runs themselves still seem to be triggered, see https://dev.azure.com/conda-forge/feedstock-builds/_build.

**Comment by xhochy** [comment]
It seems like this is working again, closing for now.
