### ISSUE TITLE
Builds not running on drone

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/status#122]
Builds are currently not being triggered on drone which causes native `linux-aarch64` builds to be silently skipped. Cross-compiled and emulated builds are unaffected.

We've contacted their support and will update this issue when we know more.

**Comment by isuruf** [comment]
To cross-compile builds add the following,

```
build_platform:
  linux_aarch64: linux_64
```

**Comment by chrisburr** [comment]
As this issue is persisting a conda-smithy release has been made to switch to emulation by default: https://github.com/conda-forge/conda-smithy/releases/tag/v3.14.3

To pick up the change feedstocks will need to be rerendered.

**Comment by beckermr** [comment]
See this announcement. We are keeping everything emulated for now. https://github.com/conda-forge/conda-forge.github.io/pull/1555
