### ISSUE TITLE
CDN cloning backlogged (new packages unavailable)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/status#123]
Currently the CDN is having issues cloning. Meaning recently uploaded packages are unavailable.

This issue has been raised with Anaconda and is currently being investigated. Will include any status updates here.

**Comment by jakirkham** [comment]
Anaconda identified the issue, implemented a fix, and reindexed the channel. Recently uploaded packages appear to be available. Closing as resolved

**Comment by h-vetinari** [comment]
Sigh, the scipy-PR for 3.10 got merged during this, and the migrator now considers all immediate scipy-children as "not resolvable". This will sort itself out in a few days, but that was really unlucky timing.
