### ISSUE TITLE
azure jobs not running

### ISSUE THREAD

**Issue by beckermr** [conda-forge/status#125]
It appears azure jobs are not running. We are working with our contacts to get this resolved.

**Comment by beckermr** [comment]
Xref: https://github.com/conda-forge/conda-forge.github.io/issues/1604

**Comment by h-vetinari** [comment]
I think that, unfortunately, this deserves a "major outage" label.

**Comment by beckermr** [comment]
Agreed! Done.

**Comment by BastianZim** [comment]
It’s working again for me.

**Comment by beckermr** [comment]
A final update here. We heard back from Azure and we were caught up in some changes they put in to fight abuse in their open platform. Hopefully, it doesn't happen again!
