### ISSUE TITLE
Travis CI queue backed up

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/status#136]
Have been seeing long queue times on Travis CI since yesterday. This can also be seen via <a href="https://app.travis-ci.com/github/conda-forge?tab=insights&timeInterval=week">Travis CI's insight tab for the org</a>. Travis CI has been notified of the issue. No ETA as of yet.

<details>

<img width="1840" alt="Screen Shot 2022-12-16 at 9 18 35 AM" src="https://user-images.githubusercontent.com/3019665/208153204-e6be612f-2832-4af8-a8ec-16af600a98b3.png">

</details>

**Comment by apidwalinsubport** [comment]
> Have been seeing long queue times on Travis CI since yesterday. This can also be seen via [Travis CI's insight tab for the org](https://app.travis-ci.com/github/conda-forge?tab=insights&timeInterval=week). Travis CI has been notified of the issue. No ETA as of yet.

**Comment by beckermr** [comment]
This has appeared to resolve itself. Shall we close it @jakirkham?

**Comment by jakirkham** [comment]
Let's give this another day. Am still seeing ~6min queue times vs. ~1min normally, which is much better than it was, but still high. Also not sure whether things just cleared due to low activity over the weekend.

**Comment by hmaarrfk** [comment]
> resolve itself

somebody took active measures to move alot of jobs to azure right?

**Comment by jakirkham** [comment]
This has largely been done in the past. So probably not that many more jobs to move.

**Comment by hmaarrfk** [comment]
I guess maybe I was just noticing a few more bugs from people not cross compiling linux too well.

**Comment by jakirkham** [comment]
Am basing that on the fact that usage of Travis informed by their metrics has been pretty consistent for the last month (including today), ~50 builds. It oscillates a bit from day-to-day, but that is pretty close to an "average" number.

**Comment by beckermr** [comment]
Still looks low as of this morning. We can keep watching it but it feels like it might be fixed.

**Comment by jakirkham** [comment]
Yeah average queue time is now ~2mins as opposed to ~6mins. That is more within the normal range. Let's close.
