### ISSUE TITLE
Feedstock uploads need token reset

### ISSUE THREAD

**Issue by beckermr** [conda-forge/status#137]
Our admin migrations bots lost a significant number of feedstock tokens, disabling uploads of feedstock builds. If your feedstock is affected, please send a request for a token reset to <a href="https://github.com/conda-forge/admin-requests">conda-forge/admin-requests</a>. We are working to reset the tokens ourselves but do not know when this will be complete.

**Comment by h-vetinari** [comment]
> Our admin migrations bots lost a significant number of feedstock tokens

Would it be possible somehow to figure out which tokens were lost, so that we don't have to discover the failing feedstocks on a case-by-case basis?

**Comment by beckermr** [comment]
We know which ones are lost and our bots are working on the fix. The issue is that the reset is slow due to api rate limits. We can only do about 75 per hour. :(

**Comment by jakirkham** [comment]
We reset tokens for ~100 feedstocks in PRs ( https://github.com/conda-forge/admin-requests/pull/639 ) & ( https://github.com/conda-forge/admin-requests/pull/642 ) and restarted CI for them. This closes out the recent upload issues

~80% of feedstocks have been migrated through the token migration

We may still see lingering issues from feedstocks not yet migrated. Though this should substantially improve things

**Comment by beckermr** [comment]
Thank you!

**Comment by h-vetinari** [comment]
Thanks a lot John!

We still need a restart (or better: a new commit by merging a PR) on the pinning repo. There's a couple of simple candidates for that, no change there over the last 2-3 days has actually gone into effect.

**Comment by jakirkham** [comment]
We shouldn't as I manually restarted all of those 😅

**Comment by jakirkham** [comment]
That said, would love to have that integrated into the token reset GHA job. Matt and I spent a while combing over the GH API docs to find something to restart CI (Azure & Travis), but didn't find anything

**Comment by h-vetinari** [comment]
My experience with a couple feedstocks is that restarts didn't work in several cases, only a new commit did.

In any case, the CI on the main branch of the conda-forge-pinning repo is red. I don't care how we get it green, but we should do that (an example of a candidate for a trivial merge: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3934).

**Comment by jakirkham** [comment]
Interesting, usually starting a new job (not restarting failed builds) worked for me

Hadn't touched that one, but here's a new job: https://app.travis-ci.com/github/conda-forge/conda-forge-pinning-feedstock/builds/259615599

**Comment by jakirkham** [comment]
Since yesterday there have been a handful of feedstocks that needed token resets. Have batched a few through (as have other maintainers). Looking at the migration it appears we are at ~90%. So think this is drawing to a close.

**Comment by jakirkham** [comment]
Last migration run was ~98% complete. Expect it will finish soonish.

**Comment by beckermr** [comment]
This is done! I went to thank everyone for their patience with us during this outage!

**Comment by BastianZim** [comment]
> That said, would love to have that integrated into the token reset GHA job. Matt and I spent a while combing over the GH API docs to find something to restart CI (Azure & Travis), but didn't find anything

Maybe this? https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs?tool=cli#re-running-failed-jobs-in-a-workflow 
It's the CLI but better than nothing.

**Comment by beckermr** [comment]
That's a great tip! Thank you!

**Comment by BastianZim** [comment]
I think it's a wrapper for https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#re-run-a-job-from-a-workflow-run and https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#re-run-failed-jobs-from-a-workflow-run based on https://github.com/cli/cli/blob/ba27e5bfb88bab29021ae0eace03348e41f0b24f/pkg/cmd/run/rerun/rerun.go#L19 which you can also call directly.

**Comment by beckermr** [comment]
That looks to be only actions and not azure

**Comment by BastianZim** [comment]
Ahh shoot yes – disregard :)
