### ISSUE TITLE
Travis builds not starting

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/status#138]
A couple of jobs on feedstocks I maintain were created today for the aarch/ppc migration, and builds like [this one](https://app.travis-ci.com/github/conda-forge/sdl2_ttf-feedstock/builds/259521790) have been waiting for almost 3h for a place in the queue, but nothing seems to start. According to the status page, travis only ran 1 job in the last 8 hours, so it does not sound like an oversubscription issue.

I was wondering if that's a known issue?

**Comment by jakirkham** [comment]
We've been having other issues today ( https://github.com/conda-forge/status/issues/137 ). Would not be surprised if the churn from that (either through CI builds or token rotation) is causing Travis CI issues

**Comment by beckermr** [comment]
Travis is really struggling at our scale. I think we're gonna have to rethink how we use Travis and how we provision feedstocks on it.

**Comment by beckermr** [comment]
How are we doing with this?
