### ISSUE TITLE
Travis builds not running

### ISSUE THREAD

**Issue by beckermr** [conda-forge/status#139]
Travis builds appear to be stopped currently. We do not have an estimate for when they will be working again.

**Comment by jakirkham** [comment]
Contacted Travis and they said we should retry any builds. If anyone is watching this issue and has a build ready to go, please let us know.

**Comment by beckermr** [comment]
Closing for now!

**Comment by jakirkham** [comment]
Can you please share an example?

**Comment by LecrisUT** [comment]
https://app.travis-ci.com/github/conda-forge/spglib-feedstock/requests

**Comment by jakirkham** [comment]
That seems like a different issue. Could you please raise an issue on that feedstock and cc core?

**Comment by LecrisUT** [comment]
[spglib-feedstock#92](https://github.com/conda-forge/spglib-feedstock/issues/92)
