### ISSUE TITLE
Many (all?) Linux builds failing due to JSON parsing failures

### ISSUE THREAD

**Issue by mattwthompson** [conda-forge/status#144]
Tracebacks might include something like 
```
critical libmamba Unable to read repodata JSON file 'pkgs/main/linux-64', error was: parse error line 593247: subdir mismatch
```
These issues were posted in the gitter channel as examples of previous

* https://github.com/mamba-org/mamba/issues/442
* https://github.com/mamba-org/mamba/issues/947

There also appears to be discussion at https://github.com/mamba-org/mamba/issues/2363

**Comment by h-vetinari** [comment]
Also: https://github.com/openSUSE/libsolv/issues/529

**Comment by jakirkham** [comment]
Is there a particular package combination that avoids this issue?

**Comment by wolfv** [comment]
Thanks! One problem is that defaults now ships noarch packages in the linux-64 subdir (in this repodata: https://repo.anaconda.com/pkgs/main/linux-64/repodata.json )
I did think that we would not use the main/defaults channel anymore in conda-forge
Another issue is that libsolv added a check at some point to make sure that subdirs line up. We could patch out that check and it would probably not have any negative side effects
(the spacy model files are noarch even though they are in the linux-64 subdir)
e.g. spacy-model-xx_sent_ud_sm-3.5.0-pyhd3eb1b0_0.tar.bz2
https://github.com/openSUSE/libsolv/blob/2fc0cb31a2010d70f3f9197189730400edbd6ef4/ext/repo_conda.c#L315-L319

this is the check in libsolv that throws the error. It's really late over here in Germany, but we could patch that away and then things should work again. Not sure how long it takes for anaconda to roll back the change (I assume it is a patch)

Hmm, looking at the patch_instructions.json (https://repo.anaconda.com/pkgs/main/linux-64/patch_instructions.json) it doesn't seem to be a patch

**Comment by beckermr** [comment]
@chenghlee @jezdez Is there a bug somewhere or is this an unannounced api change?

**Comment by rosepearson** [comment]
Thanks for the info @wolfv  and team. Great work on the tools and looking forward to the fix when it comes through.

**Comment by jakirkham** [comment]
Ok after some group debugging our understanding is some packages `noarch` packages were added to the `defaults` channel recently. However they were added under the `linux-64` subdir of the repo instead of `noarch`. This in turn causes `mamba` an issue when parsing this data, which is in turn what we see

The reason this comes up is the `defaults` channel is still added in our Docker images. However AIUI this a remnant from before `conda-forge` was a self-contained channel. Our proposed fix is to drop the `defaults` channel from the Docker image ( https://github.com/conda-forge/docker-images/pull/236 ). As it takes a bit for these images to build (and we would like to confirm on CI that they do work before shipping), this will take a little bit to get through. That said, it should be relatively straightforward to restart CI once new images are available

**Comment by jakirkham** [comment]
Anaconda has also patched the `defaults` channel to address the metadata issue `mamba` encountered

**Comment by jakirkham** [comment]
Meaning how the packages were uploaded such that they were added to the `linux-64` repodata instead of the `noarch` repodata? Yes we don't know that. Anaconda will likely need to investigate further as part of post-mortem

**Comment by beckermr** [comment]
Right. Hopefully the same bug doesn't cause some other crazy thing until anaconda can investigate.

**Comment by jakirkham** [comment]
Yeah one follow up item may be running tests on the repodata periodically (maybe creating some environments with different tools). Ultimately spec-ing out the repodata format and adding validation steps would be ideal

In any event thinking the Docker image change makes sense regardless for this reason

**Comment by h-vetinari** [comment]
Thanks everyone for solving this one quickly! ❤️

**Comment by jakirkham** [comment]
Agreed thanks everyone for coming together on this one 🙏

With the Docker images now out and the Anaconda repodata patch in place, going to close this out as resolved

Though if anyone spots a lingering issue (after restarting CI 😉), please leave a comment here with details about the issue and we can follow up 🙂

**Comment by jezdez** [comment]
> @chenghlee @jezdez Is there a bug somewhere or is this an unannounced api change?

This wasn't an API change, no, but a human error basically, and we're working to rectify the procedural issues that let this happen. Thanks everyone for your patience and understanding!
