### ISSUE TITLE
Builds on osx & win failing

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/status#147]
It appears there's some wide-spread breakage in osx & windows builds happening since about 20min; happens on every PR I've looked at that started since then. Failure looks like:

```
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_index/index/__init__.py", line 347, in _get_resolve_object
    sd._process_raw_repodata(repodata_copy)  # type: ignore
TypeError: SubdirData._process_raw_repodata() missing 1 required positional argument: 'state'
```

This happens before the actual build step of a given feedstock even runs, during the "Attempting to finalize metadata for <xyz>" phase.

While it's pure speculation, I have a suspicion that it might be related to https://github.com/conda-forge/miniforge/pull/466 (at least, no other relevant packages that I checked seemed to have been updated recently).

CC @conda-forge/core

**Comment by jakirkham** [comment]
Interesting have not noticed this on macOS builds I've been working on (for [example]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=735051&view=logs&j=4b3757f9-99c5-5891-6c0c-93d7030cdf7d&t=f047df50-a233-5ae9-bf8f-c7dd8e5684ad )). Not saying there are not issues, but perhaps the scope is more limited

Could you please share some examples where this occurs?

**Comment by h-vetinari** [comment]
From what I can tell, Isuru marked the problematic [release](https://github.com/conda-forge/miniforge/releases) as a pre-release, so presumably it shouldn't get pulled into builds anymore. I first saw this in https://github.com/conda-forge/opencv-feedstock/pull/363, but when I checked the overall [pipelines](https://dev.azure.com/conda-forge/feedstock-builds/_build) tab for conda-forge, the first 5 builds I checked were all affected.

I restarted the builds in opencv and it seems this has fixed the fallout.

**Comment by h-vetinari** [comment]
For me it's fine to close this issue. I don't doubt the breakage will be investigated before the trigger is pulled a second time. Thanks for the quick response everyone!
