### ISSUE TITLE
Nesting migrator anchors is invalid HTML

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/status#150]
It appears that [nested links are invalid HTML]( https://www.w3.org/TR/html401/struct/links.html#h-12.2.2 ), which is IIUC how the individual migrators are rendered now. This explains why linking to other migrators doesn't work currently.

Think it may be worth considering another approach. Some discussion of options in [this SO question]( https://stackoverflow.com/q/13052598 ). Also it might be worth considering just putting all the migrators on its own page. So there is no issue with how much of the page is used by them.

**Comment by beckermr** [comment]
I'm confused. Can you post the offending snippets?

**Comment by jakirkham** [comment]
It's hard to do as IIUC they are dynamically generated

https://github.com/conda-forge/status/blob/b52a8c2d1f1565a3c92d8c6fd15748843765137e/site/migrator.js#L327-L334

**Comment by beckermr** [comment]
Ok. I'm happy to work on this but I don't understand the problem.

**Comment by jakirkham** [comment]
Sure clicking on any migrator under "Other Migrations" provides an anchor for that migration ( for example, the `ffmpeg6` migration: https://conda-forge.org/status/#ffmpeg6 ). However as this is within the "Other Migrations" anchor ( https://conda-forge.org/status/#other_migrations ), it is invalid HTML, which causes linking to these migrations to not work

**Comment by beckermr** [comment]
I think the issue is actually that the anchor doesn't exist until you load the other migrators by clicking the header. The migrator anchors for the long-running migrations work fine.

**Comment by beckermr** [comment]
I am sure a better JS dev would know how to force that click when people request the anchor. I do not.

**Comment by jakirkham** [comment]
It's still nested though

**Comment by jakirkham** [comment]
Yeah there are are some workarounds proposed in the SO question. Though agree those are harder to do

What if we just create a different page for all migrations and link there? Maybe this would be easier to tackle and avoid this issue

**Comment by beckermr** [comment]
I don't follow the nesting thing at all.

**Comment by jakirkham** [comment]
Do we agree the links to migrators under "Other Migrations" don't work?

If so, think that is the relevant thing. Then this discussion becomes about what to do about technically

**Comment by beckermr** [comment]
Yep. 100%  im happy with a second page of folks want.

**Comment by beckermr** [comment]
I pushed a commit that will sort the long migrator lists to the bottom of the page and leave them open. The links work fine on my machine. This was easier than making a second new page.

**Comment by jakirkham** [comment]
That seems like a good solution. Thanks Matt! 🙏

Would it make sense to have a link right below long running migration  to jump to the other migrations?

**Comment by beckermr** [comment]
Sure!

**Comment by jakirkham** [comment]
PR ( https://github.com/conda-forge/status/pull/151 ) seem to do the trick. Please take a look 🙂

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/status/pull/152 )
