### ISSUE TITLE
Package uploads are failing

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/status#153]
It seems to affect most (all?) feedstocks: for a CI run on `main`, the built artefacts fail during publication:
```
ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
copy results:
{}
Failed to upload due to copy from staging to production channel failed. Trying again in 10 seconds
```

**Comment by h-vetinari** [comment]
@beckermr suspected the heroku server as a reason behind this.

**Comment by beckermr** [comment]
It appears the server got into a bad state after heroku restarted it. I restarted it again and it is now working. This happens from time to time for reasons I don't understand.
