### ISSUE TITLE
Migrators not showing up on status page?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/status#154]
The current migrator statuses all appear empty

<hr>

<img width="662" alt="Screenshot 2023-08-09 at 12 33 14 PM" src="https://github.com/conda-forge/status/assets/3019665/3ccbfcb2-aa52-412f-ba84-b26b4dfa57e9">

<hr>

<img width="781" alt="Screenshot 2023-08-09 at 12 33 42 PM" src="https://github.com/conda-forge/status/assets/3019665/aa7378ce-91ba-496d-bbc8-b34a72c87705">

**Comment by beckermr** [comment]
It is working on my phone.

**Comment by jakirkham** [comment]
Ah weird. It is now working for me too

Not sure what was happening before. Even tried busting the browser cache to no avail

Anyways will go ahead and close

Thanks Matt! 🙏
