### ISSUE TITLE
Windows uploads are failing

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/status#157]
conda-smithy 3.26, released yesterday, introduced a regression that prevents Windows packages from being uploaded correctly.

**Comment by jaimergp** [comment]
Root cause identified. Fix available at https://github.com/conda-forge/conda-smithy/pull/1770.

An additional mitigation to avoid having to rerender the feedstocks is being prepared.

**Comment by jaimergp** [comment]
Feedstocks that have failed Windows uploads due to this issue (most recent failures first):

- [ ] [lstmcpipe-feedstock](https://github.com/conda-forge/lstmcpipe-feedstock)
- [ ] [assimulo-feedstock](https://github.com/conda-forge/assimulo-feedstock)
- [ ] [fluidfft-feedstock](https://github.com/conda-forge/fluidfft-feedstock)
- [ ] [r-fastverse-feedstock](https://github.com/conda-forge/r-fastverse-feedstock)
- [ ] [tofu-feedstock](https://github.com/conda-forge/tofu-feedstock)
- [ ] [rasterio-feedstock](https://github.com/conda-forge/rasterio-feedstock)
- [ ] [evomsa-feedstock](https://github.com/conda-forge/evomsa-feedstock)
- [ ] [deno-feedstock](https://github.com/conda-forge/deno-feedstock)
- [ ] [cloud-sql-proxy-feedstock](https://github.com/conda-forge/cloud-sql-proxy-feedstock)
- [ ] [rust-feedstock](https://github.com/conda-forge/rust-feedstock)
- [ ] [openlineage-sql-feedstock](https://github.com/conda-forge/openlineage-sql-feedstock)
- [ ] [cryptography-feedstock](https://github.com/conda-forge/cryptography-feedstock)
- [ ] [geoana-feedstock](https://github.com/conda-forge/geoana-feedstock)
- [ ] [chromadb-feedstock](https://github.com/conda-forge/chromadb-feedstock)
- [ ] [r-apcluster-feedstock](https://github.com/conda-forge/r-apcluster-feedstock)
- [ ] [terragrunt-feedstock](https://github.com/conda-forge/terragrunt-feedstock)
- [ ] [cbor2-feedstock](https://github.com/conda-forge/cbor2-feedstock)
- [ ] [intbitset-feedstock](https://github.com/conda-forge/intbitset-feedstock)
- [ ] [openssl-feedstock](https://github.com/conda-forge/openssl-feedstock)
- [ ] [time-machine-feedstock](https://github.com/conda-forge/time-machine-feedstock)
- [ ] [r-catboost-feedstock](https://github.com/conda-forge/r-catboost-feedstock)
- [ ] [river-cpp-feedstock](https://github.com/conda-forge/river-cpp-feedstock)
- [ ] [odbc2parquet-feedstock](https://github.com/conda-forge/odbc2parquet-feedstock)
- [ ] [r-rcppint64-feedstock](https://github.com/conda-forge/r-rcppint64-feedstock)

**Comment by beckermr** [comment]
Do we need to mark 3.26 as broken?

**Comment by beckermr** [comment]
We should wait for 3.26.1 to hit the CDN though.

**Comment by jaimergp** [comment]
With the conda-forge-ci-setup patch it's not broken anymore (since it accepts the "malformed" feedstock name)

**Comment by jaimergp** [comment]
Windows uploads are going through now (e.g. [`assimulo`](https://github.com/conda-forge/assimulo-feedstock)). I'll remove the label for now and keep this open so I can update the list above and ensure that no Windows packages were left behind. Apologies for the downtime!

**Comment by jaimergp** [comment]
Closing as complete since all uploads were retried to success.
