### ISSUE TITLE
New package uploads not available

### ISSUE THREAD

**Issue by njzjz** [conda-forge/status#158]
### Comment:

It looks like a CDN issue:

![image](https://github.com/conda-forge/status/assets/9496702/3f8b88c1-2c8b-452f-9db4-7cf09b332790)

**Comment by jakirkham** [comment]
Thanks Jinzhe! 🙏

Have raised here: https://github.com/conda/infrastructure/issues/851

**Comment by h-vetinari** [comment]
CDN sync should be functional again, removing label

**Comment by jakirkham** [comment]
Going to readd the label and close the issue instead. That way users can hopefully see there was an addressed issue (in case they are still running into problems related to it)
