### ISSUE TITLE
Automerge is not working

### ISSUE THREAD

**Issue by xhochy** [conda-forge/status#173]
See e.g. https://github.com/conda-forge/eslint-plugin-react-feedstock/actions/runs/8303078617/job/22726546836

```
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by beckermr** [comment]
Ah ok. I noted this yesterday here https://github.com/conda-forge/automerge-action/issues/33 but I did not know if it was transient or not. I'll take a look.

**Comment by beckermr** [comment]
The fix should be here: https://github.com/conda-forge/automerge-action/pull/34

**Comment by beckermr** [comment]
I'm going to close for now. If it is still broken, please reopen.

**Comment by xhochy** [comment]
Thank you @beckermr !
