### ISSUE TITLE
Travis CI linux-ppc64le runners failing

### ISSUE THREAD

**Issue by mfansler** [conda-forge/status#178]
There is an ongoing issue with Travis CI running **linux-ppc64le** jobs. This is impacting all R feedstocks and may be more widespread. The issue presents as indefinite queuing that eventually times out. The last known successful job *start* on a Travis CI **linux-ppc64le** runner was April 30, 2024. The issue has been reported to Travis CI and their engineers are looking into it.

**Comment by hoechenberger** [comment]
A Python feedstock with seemingly the same problem (just to point out it's probably not just R packages):
https://github.com/conda-forge/trx-python-feedstock/pull/7
