### ISSUE TITLE
Linux builds with `yum_requirements.txt` currently failing

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/status#180]
Recently we migrated from CentOS 6 to CentOS 7 as the minimum Linux in conda-forge: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6070

However due to [CentOS 7 reaching EOL yesterday]( https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/ ), the typical RPM mirrors have been removed

Atm this is disrupting `yum_requirements.txt` based builds on Linux. We are working on switching to RPM archive mirrors. As that work progresses, will post updates

**Comment by jakirkham** [comment]
Fixed Docker images have been deployed

Running some tests to see if this has indeed been resolved

**Comment by jakirkham** [comment]
Appears to be working. Closing as resolved

Please make sure to rerun CI where the issue has occurred

If you still see issues after, please let us know

Thanks for your patience as we worked through this issue! 🙏

**Comment by hmaarrfk** [comment]
Amazing work
