### ISSUE TITLE
All jobs on Azure Pipelines are failling due to missing resources

### ISSUE THREAD

**Issue by xhochy** [conda-forge/status#181]
All jobs are failing with

```
##[error]No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request
```

**Comment by MementoRC** [comment]
The issue seems to have been resolved, PR went through

**Comment by h-vetinari** [comment]
Back online since ~12h, closing this issue. Sorry for the outage everyone, it was out of our hands.

**Comment by nsoranzo** [comment]
Can a conda-forge admin please restart https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=970388&view=results so that the galaxy-util 24.1.1 package is uploaded to Anaconda?

**Comment by valeriupredoi** [comment]
cheers folks! All fixed for us too, this has to be one of the most popular issues I've seen, four days old and tens upon tens of reactions, and referencing - GitHub-TikTok :grin:
