### ISSUE TITLE
Autotick Bot is failing

### ISSUE THREAD

**Issue by mfansler** [conda-forge/status#182]
The `bot-bot` workflow has been failing with an `API rate limit exceeded` error since 2024-07-10 19:18:08 UTC. R 4.4/UCRT migration Pull Requests are not being generated.

https://github.com/regro/cf-scripts/issues/2838

**Comment by beckermr** [comment]
FYI the bot is making PRs: https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+author%3Aregro-cf-autotick-bot+archived%3Afalse+

We'll have to wait for the token to recover.

**Comment by mfansler** [comment]
Ah sorry - guess I misinterpreted. I was judging based that we have not seen any subsequent R 4.4/UCRT migrations since the failures started: https://github.com/search?q=org%3Aconda-forge+%22Rebuild+for+r-base+4.4+and+UCRT+mingw+toolchain%22&type=pullrequests&s=created&o=desc

Is that a different bot?

**Comment by beckermr** [comment]
I may have been too fast as well. The bot seems to not be able to reach all of the migrators for PRs because the token's API requests keep running out. I'll need to investigate.

**Comment by mfansler** [comment]
Closing, as this now appears resolved.
