### ISSUE TITLE
Azure degraded

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/status#184]
Azure went [completely offline]( https://status.dev.azure.com ). This is affecting the service outside conda-forge as well. It is starting to improve after Azure began mitigating. CI using Azure may remain sluggish or not run until this is fully resolved

**Comment by h-vetinari** [comment]
Quite a sight to behold:

![image](https://github.com/user-attachments/assets/53f751bc-cd28-4d18-9ca9-e1b71a5871ef)

![image](https://github.com/user-attachments/assets/f5fcad45-7f69-42b8-981c-0fd673131ad9)

At least the underlying [issue](https://azure.status.microsoft/en-us/status) seems to be on track towards recovery:

![image](https://github.com/user-attachments/assets/2f60a575-75c8-4f81-8184-e357f2f28185)

**Comment by jakirkham** [comment]
It's starting to improve. Going to change to degraded. May take a bit before things get back to normal

**Comment by dalthviz** [comment]
Just in case, things are running for me now:

![image](https://github.com/user-attachments/assets/9b8ee7bf-ab69-4b63-8834-603eb514df83)

**Comment by jakirkham** [comment]
Restarted the open PRs

Haven't done anything for the merged ones (am on my phone)

**Comment by jakirkham** [comment]
Most appear to have started on their own. These 2 need fresh builds as they never started on `main`:

* https://github.com/conda-forge/arraykit-feedstock
* https://github.com/conda-forge/gpstime-feedstock

Edit:

Also found this

* https://github.com/conda-forge/dgl-feedstock/issues/47

**Comment by jakirkham** [comment]
This appears to have resolved. Closing...
