### ISSUE TITLE
Azure build jobs not being triggered

### ISSUE THREAD

**Issue by mfansler** [conda-forge/status#188]
Pull Requests in some feedstocks are not triggering Azure build jobs. This has been observed on both `staged-recipes` and individual feedstocks since at least 27-Oct 5:43 AM GMT. Restarting CI (close-open) does not resolve the issue. Travis CI jobs do appear to get triggered. Some feedstocks additionally trigger an (unusual) Appveyor job that fails.

Maintainers are reminded to double-check that "passing" checks on PRs include build jobs before considering merging.

It is hypothesized that this is related to an Azure wide issue. Please see https://status.dev.azure.com/_event/559260722.

**Comment by danielnachun** [comment]
I'll note here that I was able to bypass the restart CI issues by simply making an empty commit for a while, but that doesn't seem to work now. 

Furthermore, for a while when restarting CI, Azure jobs would still get triggered but fail almost instantly due to what I believe was a "git status 128" error.  I saw this happen sporadically once in `staged-recipes` but it went away after restarting CI.  I'm not sure if these issues are connected to or informative for the current issue.  Hopefully this gets resolved soon!  Azure itself reports no outages right now.

**Comment by mfansler** [comment]
Fortunately, `bot-automerge` doesn't seem to proceed. 😅 Perhaps maintainers should be advised to convert affected PRs to "Draft", to guard against accidental untested merges?

**Comment by mfansler** [comment]
***NB:** Moving these examples out of the notification post since they were taking up Status page real estate.* 

## Example PRs

- [x] https://github.com/conda-forge/staged-recipes/pull/28024
- [ ] https://github.com/conda-forge/r-startr-feedstock/pull/18
- [ ] https://github.com/conda-forge/r-mlr3tuning-feedstock/pull/30
- [ ] https://github.com/conda-forge/r-memisc-feedstock/pull/8
- [ ] https://github.com/conda-forge/r-strawr-feedstock/pull/6
- [ ] https://github.com/conda-forge/r-cairo-feedstock/pull/41
- [ ] https://github.com/conda-forge/r-primme-feedstock/pull/19
- [x] https://github.com/conda-forge/qt-wayland-feedstock/pull/33
- [ ] https://github.com/conda-forge/csp-feedstock/pull/45
- [x] https://github.com/conda-forge/r-hmisc-feedstock/pull/38
- [x] https://github.com/conda-forge/polars-feedstock/pull/281

*Feel free to edit.*

**Comment by lesteve** [comment]
Just to say that a similar behaviour has been seen in scikit-learn and joblib so this is likely not conda-forge specific.

**Comment by jdblischak** [comment]
> this is likely not conda-forge specific

Definitely not conda-forge specific. There is a known incident being tracked at https://status.dev.azure.com/_event/559260722

**Comment by xylar** [comment]
> Meanwhile, users can try triggering the pipelines manually.

Sadly not an option for most maintainers here.

**Comment by h-vetinari** [comment]
> Sadly not an option for most maintainers here.

And even if that were an option, we shouldn't use it. That's because triggering a run in the Azure Pipelines UI for commit from a PR has a big footgun built-in, in the sense that it would run _as if it had been merged_, in other words, packages would get published.

**Comment by xylar** [comment]
Oh, wow, good that it's not an option for maintainers, then!

**Comment by hmaarrfk** [comment]
Hmm so an azure build takes at least 2 hours!![Image](https://github.com/user-attachments/assets/9242575c-44ef-479a-8f76-0d0841f699a1)

**Comment by mfansler** [comment]
The hotfix [has been rolled out](https://status.dev.azure.com/_event/559260722) as of 29-Oct 07:40 AM GMT. However, I have not yet been able to confirm a successful build. Close-Reopen is occasionally generating aberrant(?) AppVeyor jobs. Also, seeing failure to fetch the feedstock PRs, e.g.:

```bash
fatal: couldn't find remote ref refs/pull/30/merge
##[error]Git fetch failed with exit code: 128
```

**Comment by beckermr** [comment]
The appveyor jobs are unrelated.

**Comment by mfansler** [comment]
✅ Affected bot PRs marked `bot-rerun` come back working now. 
✅ Affected `staged-recipes` PRs are working after merge from `main`.
❓ Other PRs may work again after pushing a commit (e.g., empty commit).

Seems like things are working again *after* the PRs "refresh" in some way.

**Comment by beckermr** [comment]
Great. I am going to close this one since Azure has marked it as done as well.

**Comment by billysuh7** [comment]
@conda-forge-admin , please restart CI
