### ISSUE TITLE
PR Builds not starting

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/status#30]
Appears CircleCI builds for PRs are not starting. No known workaround at this time.

**Comment by jakirkham** [comment]
Have emailed support.

**Comment by jakirkham** [comment]
cc @conda-forge/core

**Comment by jakirkham** [comment]
I have receive a reply. Please see below.

> We corrected a bug where we were allowing forked PR builds to run on Open Source projects even if that feature was disabled.
>
> To go back to the functionality you are used to, please enable `Permissive building of fork pull requests` in the advanced settings for the project on CircleCI.

In short, it sounds like we were relying on a bug for PRs to work at all.

**Comment by jakirkham** [comment]
Should note that under this setting I see the following text.

> There are serious security concerns with this setting (see the documentation for details.) If you have SSH keys, sensitive env vars or AWS credentials stored in your project settings and untrusted forks can make pull requests against your repo, then this option isn't for you!

Not something that inspires confidence. 😞 This may mean things deploy prematurely from PRs if these environment variables are exposed. Am asking CircleCI about this.

**Comment by jjhelmus** [comment]
I do not think there are any security concerns for us.  According to that document:

```
The variables configured via the circle.yml will be available in the fork PR builds (as they have access to the same circle.yml file); the values configured through the UI will not be visible to the fork PRs
```

I believe that the anaconda.org upload token is stored as a secure variable via the UI and therefore is not visible in PRs.  This would be the only variable that I can think of that needs to be protected.

**Comment by jjhelmus** [comment]
Going to `Settings` (the gear icon), `Advanced Settings` and switching the `Permissive building of fork pull requests` setting to `On` does in fact re-enable Circle CI build on pull requests.  I turned this on in the `python-feedstock` and the PR I submitted is building on Circle (conda-forge/python-feedstock#96).  

I think this will need to be done for all feedstocks.  It might be worthwhile to ask Circle CI if they can do this for all the `conda-forge` repositories as manually updating 1000+ settings will be a pain.

**Comment by jakirkham** [comment]
> I do not think there are any security concerns for us.

I hope you are right. Which document are you referring too?

> It might be worthwhile to ask Circle CI if they can do this for all the `conda-forge` repositories as manually updating 1000+ settings will be a pain.

Also am asking about that too. It seems they don't have an API for us to do it. So even if we fix all of our repos, we will be stuck doing this manually when it comes to new repos.

**Comment by jjhelmus** [comment]
I'm looking at the [Building Pull Requests from forks](https://circleci.com/docs/fork-pr-builds/) document.  The odd part is that according to that document pull request builds should be turned on for public GitHub repositories (including conda-forge) by default.  I would be interested in seeing if `Permissive building of fork pull requests` is turned on for a newly created feedstock or not.

**Comment by jakirkham** [comment]
Should be easy to find out. 😉

**Comment by jjhelmus** [comment]
Thanks for looking into this @jakirkham.  I have some day job work that needs attention but will be back tonight to keep the ball moving towards `conda build` 2!

**Comment by jjhelmus** [comment]
So apparently turning on `Permissive build of fork pull requests` also exposes the Environment Variables for the repository to pull requests which results the package being uploaded from the pull request's Circle CI builds rather than after merging, for example in this [glib build](https://circleci.com/gh/conda-forge/glib-feedstock/49?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). 

That is a serious security concern as packages are getting uploaded without review and the upload token could can be exposed by a malicious PR.

**Comment by jakirkham** [comment]
Thanks for confirming this. Will ask what we can do about it.

**Comment by jjhelmus** [comment]
Ahh wait.  Apparently this behavior is what [is expected](https://circleci.com/docs/fork-pr-builds/#unsafe-fork-pr-builds) when the `Project fork pull requests` toggle is set.  So we should definitely **NOT** be doing that, sorry I suggested it.

Still does not explain why pull requests were not triggering builds.

**Comment by jakirkham** [comment]
> Still does not explain why pull requests were not triggering builds.

The explanation is we were relying on a "bug" to get pull requests to work before. Yesterday they "fixed" the "bug". Though IMHO it was a [feature]( https://xkcd.com/1172/ ) and they just broke it. 😢

**Comment by jjhelmus** [comment]
> Though IMHO it was a feature and they just broke it.

Yes, and a very important feature at that.  It looks like the same thing is happening with the Circle CI build on SciPy.  I've opened an issue (scipy/scipy#6839) to track the issue there as well.

**Comment by jakirkham** [comment]
CircleCI said they are looking into it. Let's wait and see what comes out of it.

**Comment by pelson** [comment]
What are CircleCI thinking?!? Why would you *ever* want to expose your secrets through forked PRs? If you do actually want them exposed, you don't need to call them secret because anybody can echo them... it is a completely illogical move for open source, and a huge bug in their design.

Do you have a GitHub issue that we can xref?

**Comment by jakirkham** [comment]
Well, they have added a setting since that appears to disable exposing your secrets in a forked PR build. FWIW that appears to be off. I might try experimenting with this in one feedstock and see how it goes.

**Comment by jakirkham** [comment]
The current workaround is to enable CircleCI on one's own fork of the feedstock or staged-recipes and push new changes to get it to trigger with the other CIs.

**Comment by jakirkham** [comment]
Should add that another consequence of this problem is that sometimes recipes pending conversion in staged-recipes will be included in CircleCI builds as we are no longer able to do proper builds of PRs, but are instead having users build on their own fork. Fortunately it should not take away from the org queue on CircleCI though.

xref: https://github.com/conda-forge/staged-recipes/pull/1373
xref: https://github.com/conda-forge/staged-recipes/pull/1486

**Comment by jakirkham** [comment]
For details on how to enable CircleCI on your own fork, please see this [doc]( http://conda-forge.github.io/docs/ciservices.html#circleci-linux ).

**Comment by jakirkham** [comment]
Was able to enable CircleCI builds on staged-recipes. To do this generally on a feedstock, one has to navigate to the repo settings on CircleCI (gear in the upper right hand corner). Then select "Advanced Settings" in the left panel. Finally enable "Build forked pull requests" only. After doing this one must close and reopen the PR. This likely requires administrative privileges on CircleCI. Screenshot below.

<img width="1552" alt="screen shot 2017-01-04 at 13 35 42" src="https://cloud.githubusercontent.com/assets/3019665/21654315/0a7cb620-d283-11e6-8f8a-82fabf7efe31.png">

**Comment by isuruf** [comment]
You can enable this setting en masse by capturing the request for changing the setting in your browser (A request to https://circleci.com/api/v1.1/project/github/conda-forge/mpc-feedstock/settings) and then replaying it by changing the repo name in the url and payload.

**Comment by jakirkham** [comment]
Yeah, what I would really like to do is get this added to `conda-smithy`. Partly so that we can roll out this change on all feedstocks. Also partly to make sure new feedstocks have the right settings.

Guessing I should try using Selenium for implementing this, but maybe that is too much for clicking one radio button. Other suggestions welcome.

On a finer grained detail, I had looked at the source before and found even though I could identify the radio button. The source did not make it very clear which radio button belonged to which setting. My concern here is if I set everything up with say radio button 9 now and they change the settings latter, we could be getting the totally wrong behavior. So it would be nice if there was a good way of finding the setting name and then the radio button next to that setting. Any suggestions on this would be appreciated.

**Comment by isuruf** [comment]
I checked and the following works.
```
curl 'https://circleci.com/api/v1.1/project/github/conda-forge/mpc-feedstock/setting?circle-token=mytoken' -X PUT -H 'Content-Type: application/json; charset=UTF-8' -H 'Accept: application/json' --data-binary '{"feature_flags":{"build-fork-prs":true}}'
```
Here mytoken needs to be replaced by a valid token.
Implemented here, conda-forge/conda-smithy/pull/420

**Comment by jakirkham** [comment]
After working with @isuruf on his proposal for `conda-smithy`, I think we have a working fix. Have used it to enable CircleCI builds for PRs on all current feedstocks. Please take a look at the PR if you are interested.

IMHO we should get this CircleCI fix in, the re-rendering index fixes, and `conda` 4.2 fixes in. Then we should be in good shape for a healthy release.

**Comment by jakirkham** [comment]
Reopening until we actually release the new `conda-smithy` that will fix this issue.

**Comment by jakirkham** [comment]
Changed to degraded performance as many feedstocks are functioning at this point.

**Comment by jakirkham** [comment]
`conda-smithy` 2.0.0 is released and in action at staged-recipes. This release includes an important fix by @isuruf that enables CircleCI builds of PRs from forks on new feedstocks. So all new feedstocks should not have this issue. Also have applied this fix to all existing feedstocks. Therefore this should no longer be a problem for any feedstocks. Will close this out.

Fine print: We are using a non-public API to do this as there is no public API for it. So it may be changed in the future without warning.

**Comment by jakirkham** [comment]
Should add that I have asked CircleCI to make this part of the Public API. We'll see what they say.
