### ISSUE TITLE
Include number of dependents for each package for the migration status

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/status#38]
This would allow us to triage which packages we try to get working during the migration.
We can compute this from the graph.

**Comment by scopatz** [comment]
I think this should be an issue on cf-scripts, because we need the data source first, in order to display it here

**Comment by CJ-Wright** [comment]
Fair

**Comment by CJ-Wright** [comment]
xref: https://github.com/regro/cf-scripts/issues/352

**Comment by CJ-Wright** [comment]
I think this is done.
