### ISSUE TITLE
Issues uploading to Anaconda

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/status#4]
It appears there are some issues uploading to Anaconda.org on all CIs. Here is a [log]( https://ci.appveyor.com/project/conda-forge/hdbscan-feedstock/build/1.0.10/job/ljwl03dcll9xitqy#L449 ) from one such failed AppVeyor upload failure. Though similar ones can be seen for all CIs. Snippet of traceback shown below. Restarting seems to sometimes fix it.

```
python ci_support\upload_or_check_non_existence.py .\recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "ci_support\upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "ci_support\upload_or_check_non_existence.py", line 106, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "ci_support\upload_or_check_non_existence.py", line 69, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "C:\conda\lib\site-packages\binstar_client\mixins\channels.py", line 29, in show_channel
    self._check_response(res, [200])
  File "C:\conda\lib\site-packages\binstar_client\__init__.py", line 200, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ('Not Found: Nothing matches the given URI ([GET] https://api.anaconda.org/channels/conda-forge/main -> 404)', 404)
Command exited with code 1
```

cc @msarahan @mcg1969

**Comment by jakirkham** [comment]
Raising for awareness of affected teams/feedstocks that have tried to deploy recently and are now having deployment issues. Feel free to track an issue locally on your feedstock until all missing packages are uploaded.

cc @conda-forge/bqplot @conda-forge/requests-futures @conda-forge/hdbscan @conda-forge/versioneer

**Comment by jakirkham** [comment]
Restarted builds for the apparently affected feedstocks. Seems to be localized to very recent updates or new feedstocks.

**Comment by jakirkham** [comment]
All of the restarted builds appear to have passed and uploaded packages FWICT. If others can confirm, that would be great. Going to go ahead and close for now assuming this is resolved.

**Comment by lmcinnes** [comment]
The Circle CI builds were having the same problem, but the AppVeyor build looks good for me now. Presumably restarting the Circle CI builds will get those working too. Thanks.

**Comment by jakirkham** [comment]
Yeah, was just noticing this with a different CircleCI [build]( https://circleci.com/gh/conda-forge/statuspage-feedstock/12 ) just now. That build was from a few days ago. Going to elevate this issue.

**Comment by jakirkham** [comment]
Raised issue ( https://github.com/Anaconda-Platform/support/issues/60 ) about this general problem.

**Comment by SylvainCorlay** [comment]
I am also missing a linux-64/py35 file on my recent build.

**Comment by jakirkham** [comment]
Try restarting the build and see if it fixes it. This has also worked for me with CircleCI builds that failed to upload.

**Comment by jakirkham** [comment]
In some cases, am also seeing a new failure when rerunning an existing build that had already uploaded. This rerunning is being done in order to resolve some of the failed uploads. This new failure suggests the problem is not strictly limited to uploading. See the traceback below for the error and this [build]( https://ci.appveyor.com/project/conda-forge/astroid-feedstock/build/1.0.2/job/h126inb8iwx02cnx#L754 ) for more details.

```
python ci_support\upload_or_check_non_existence.py .\recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "ci_support\upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "ci_support\upload_or_check_non_existence.py", line 106, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "ci_support\upload_or_check_non_existence.py", line 69, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "C:\conda\lib\site-packages\binstar_client\mixins\channels.py", line 28, in show_channel
    res = self.session.get(url)
  File "C:\conda\lib\site-packages\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "C:\conda\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\conda\lib\site-packages\requests\sessions.py", line 628, in send
    r.content
  File "C:\conda\lib\site-packages\requests\models.py", line 755, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\conda\lib\site-packages\requests\models.py", line 679, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Command exited with code 1
```

**Comment by jakirkham** [comment]
Appears your feedstock was affected as well, @conda-forge/cssutils. Have restarted the CircleCI build.

**Comment by jakirkham** [comment]
Was starting to look like things were stabilizing as I hadn't seen this issue for awhile. However, saw this [build]( https://ci.appveyor.com/project/conda-forge/gdal-feedstock/build/1.0.226/job/evs1m32fyd71wjwl#L4941 ) from `gdal` that is struggling with a related problem.

cc @conda-forge/gdal

**Comment by jakirkham** [comment]
Also happened with some `curl` [builds]( https://ci.appveyor.com/project/conda-forge/curl-feedstock/build/1.0.20 ) recently.

cc @conda-forge/curl

**Comment by jakirkham** [comment]
Appears `pysocks` suffered from this in yesterday's [builds]( https://ci.appveyor.com/project/conda-forge/pysocks-feedstock/build/1.0.1 ). Have restarted them.

cc @conda-forge/pysocks

**Comment by jakirkham** [comment]
Affecting `sphinx` on both [CircleCI]( https://circleci.com/gh/conda-forge/sphinx-feedstock/7 ) and [AppVeyor]( https://ci.appveyor.com/project/conda-forge/sphinx-feedstock/build/1.0.7 ). Have restarted both.

cc @conda-forge/sphinx

**Comment by jakirkham** [comment]
Can confirm this is happening with all CIs now thanks to being able to track down this issue with Travis CI. ( https://github.com/conda-forge/line_profiler-feedstock/issues/6 ) Have already triggered a rebuild to get the missing packages.

cc @conda-forge/line_profiler

**Comment by jakirkham** [comment]
It looks like we may need some improvements to how we are doing uploads. This is documented briefly in issue ( https://github.com/conda-forge/conda-smithy/issues/270 ). It relies on a new Anaconda API that is going through some testing before it rolls out in the next day or two.

**Comment by jakirkham** [comment]
Turns out this issue goes back several weeks as demonstrated by this [failure]( https://circleci.com/gh/conda-forge/pyflakes-feedstock/3 ).

**Comment by jakirkham** [comment]
FWIW I haven't seen this issue really at all today. So maybe things are already improving.

**Comment by jakirkham** [comment]
This is still persisting. Here is a recent [failure]( https://circleci.com/gh/conda-forge/yarg-feedstock/1 ).

**Comment by jakirkham** [comment]
Seeing an uptick in this issue of late.

**Comment by vamega** [comment]
I think I'm seeing another instance of this issue at: https://github.com/conda-forge/yapf-feedstock/pull/3

**Comment by jakirkham** [comment]
That's a different issue. It's fixed by [re-rendering]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with a newer version of `conda-smithy`. Please try that and see if it fixes it.

**Comment by jakirkham** [comment]
On another note, we have released a new copy of `conda-smithy` that should address the upload issue that was causing us difficulties before. If you encounter this issue, also please try re-rendering. Am going to close this as we have hopefully fixed it. If not please ping us, and we can open a fresh issue. Thanks. 😄
