### ISSUE TITLE
Travis CI OS X Backlog

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/status#6]
Seems that there is some serious issue affecting Travis CI builds and causing them to wait for long periods on the queue. Have raised this issue upstream as ( https://github.com/travis-ci/travis-ci/issues/6515 ) to see if they have any ideas as to what is going on and if we can get it fixed.

For the meantime, I'd like to ask people to nice builds. If you see multiple builds for a PR at staged-recipes, please cancel all older version of it. If you are planning any large running builds, please hold off on them until we can track down this issue. It does seem some builds are getting processed, but it appears to be very slowly and long after they were initiated.

Please bear with us as we try to sort out this issue.

**Comment by jakirkham** [comment]
Reducing to degraded as we seem to actually have some things running on the queue now. Also looks like the number of jobs running is starting to fall off. Will continue to monitor the situation.

**Comment by jakirkham** [comment]
Travis CI has now [announced]( https://www.traviscistatus.com/incidents/4mvp857qx8bw ) that they are stopping all OS X builds due to instability in their OS X infrastructure. Upgrading this to major outage.

**Comment by jakirkham** [comment]
Adding staged-recipes to this outage as conversions to feedstocks occur on Travis CI. So they will similarly be blocked until Travis CI comes back online.

**Comment by jakirkham** [comment]
It appears Travis CI is re-enabling OS X builds and are starting to work through the backlog. Downgrading to degraded performance. Will provide more updates as this progresses.

**Comment by jakirkham** [comment]
Have removed staged-recipes as they have cleared. Feel free to close this when you are comfortable with Travis CI's progress.

**Comment by jakirkham** [comment]
This seems to be resolved now. Going to go ahead and close this out. If people are still having issues, please let us know.

**Comment by rainwoodman** [comment]
Hi, there seem to be a long backlog on travis of staged-recipes again. Also how do I cancel the expired PRs? There is no such option from my travis login.

**Comment by jakirkham** [comment]
> ...there seem to be a long backlog on travis of staged-recipes again.

This status issue is on a different problem with Travis CI a long time ago. If there are new issues, I would recommend raising one. Though we are certainly aware of backlog issues with Travis CI that have been occurring recently.

> ...how do I cancel the expired PRs? There is no such option from my travis login.

Travis CI does not extend that privilege to anyone that does not have write access to the repo. I had put together a script ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/52 ) that would terminate old PR builds early and could be used at staged-recipes ( https://github.com/conda-forge/staged-recipes/pull/2264 ) or feedstocks (once the dust settles on the first two). However, it seems to be stuck in discussion ATM. Feel free to nudge it along if you think it is important.

**Comment by rainwoodman** [comment]
It's alright. The backlog is gone. Thanks for explaining about the PR privilege. It is indeed nice to automatically terminate old PR builds early, but probably not very urgent now. But it appears its the best not to enable travis build of the fork -- because that would add another build task.

**Comment by jakirkham** [comment]
Well this problem seems to show up on a weekly basis during the work week. So IMHO this is a big problem as it mucks with people's ability to get work done. That said, you are right it goes away on the weekend.

There are pros and cons to enabling on your fork. Pro being it is on your own queue vs conda-forge's. Con it still adds to the overall Travis CI queue and it fails to do things like test on the merge commit. Probably not worthwhile to enable Travis CI on your fork in the end.
