### ISSUE TITLE
either remove status indicator list at bottom or make them live somehow

### ISSUE THREAD

**Issue by beckermr** [conda-forge/status#65]
Right now we keep a bunch of status indicators on the page that are always green. This is confusing and I think sends the wrong message. This is especially true for things like the linter bot which is pretty flaky these days.

**Comment by scopatz** [comment]
I think they are "live" if you create issues or something.  @jakirkham might know more

**Comment by beckermr** [comment]
Right yeah, I read that in the docs for the package. It is just that we don't actually create issues and when one of us tried it didn't work.

**Comment by jakirkham** [comment]
GitHub adds these for GitHub pages. I don't think we have much control of them. That said, they are useful when GitHub fails to render the page completely as we at least get some indication of that.

**Comment by beckermr** [comment]
Huh? I think we are talking about different things. I am talking about these

<img width="867" alt="Screen Shot 2020-01-30 at 1 33 56 PM" src="https://user-images.githubusercontent.com/5296416/73483550-39e09980-4365-11ea-8b97-8fb78210356e.png">

These are part of the statuspage.js package.

**Comment by scopatz** [comment]
Yep that is what I am talking about.

**Comment by jakirkham** [comment]
Sorry misunderstood. Thought this was referring to the commit message status.

The idea is when one files an issue and labels it with a category and a status. The status page will be updated to reflect that. Additionally the contents of that issue are included on the webpage along with any comments posted afterwards.

Ultimately it's on us to create those issues to keep the statuses relevant. I did this for a while and was hoping it would catch on. Guess it never did. Are you interested in helping keep this up-to-date? 🙂

**Comment by beckermr** [comment]
I am not. :) 

I think we should automate any information we want to be here and then remove the rest.

For example, we could show the current status of the staged recipes travis-ci job and maybe scrape some meta-statuses from key services like anaconda etc if we can get them.

**Comment by jakirkham** [comment]
Ah ok. I may have missed your proposal previously.

All of that sounds reasonable. I think this was my long term hope here. Just never had time to do it unfortunately.

Are there APIs that you can see that would support this interaction smoothly?

**Comment by beckermr** [comment]
I am looking around. Many services publish RSS feeds of their status. Badges for ci services work well too. I cannot find a status for anaconda.org. So I think we can automated the big stuff.
