### ISSUE TITLE
AppVeyor API blocking conversion

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/status#7]
AppVeyor API registration error with `itsdangerous` is blocking feedstock conversion. Will also result in `itsdangerous` showing up in PRs. Users are recommended to merge with `master` and remove `itsdangerous` from their PRs. Snippet of the traceback shown below. Several restarts of the conversion step have been tried without success. 

```
CI Summary for conda-forge/itsdangerous-feedstock (can take ~30s):
 * conda-forge/itsdangerous-feedstock already enabled on travis-ci
 * conda-forge/itsdangerous-feedstock enabled on CircleCI
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.0.3', 'console_scripts', 'conda-smithy')()
  File "/home/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/home/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 164, in __call__
    ci_register.add_project_to_appveyor(owner, repo)
  File "/home/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 114, in add_project_to_appveyor
    response.raise_for_status()
  File "/home/travis/miniconda/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ci.appveyor.com/api/projects
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/home/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/tmp/tmpw0ne44uj__feedstocks/itsdangerous-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

cc @pelson

**Comment by jakirkham** [comment]
After several restarts and a bit of time this resolved itself. However, this is hardly the first time I have seen this issue today or in general with AppVeyor's API. Maybe we need to use a similar strategy to one used with Travis CI's API.

**Comment by jakirkham** [comment]
Seeing a recurrence of this issue. See this [build]( https://travis-ci.org/conda-forge/staged-recipes/builds/157257319#L307 ) as an example.

**Comment by pelson** [comment]
In summary: AppVeyor are issuing a http 500 error intermittently when attempting to create a feedstock.

(For the status page, this is probably all that is needed, right @jakirkham?)

**Comment by jakirkham** [comment]
Yeah I'm still trying to find a healthy balance. In any event staged-recipes is cleared, so closing this out again.

**Comment by jakirkham** [comment]
xref: https://github.com/appveyor/ci/issues/1045

**Comment by isuruf** [comment]
Seeing this again. Maybe appveyor is rate limiting the API
