### ISSUE TITLE
display bot version PR backlog

### ISSUE THREAD

**Issue by beckermr** [conda-forge/status#75]
We should display our bot version PR backlog. 

cc @conda-forge/bot

**Comment by CJ-Wright** [comment]
Does this include PRs that are failing because we can't hash, or just we haven't created because of self imposed constraints?

**Comment by beckermr** [comment]
Well I’d be nice to classify them as well but for now any new version entry in the graph

**Comment by CJ-Wright** [comment]
Ok, do you expect the information to produce actions?

**Comment by beckermr** [comment]
😄 I'm not sure what you mean exactly. 

I want this exposed so that I can easily keep track of it without digging into the CI logs.

**Comment by CJ-Wright** [comment]
Ok, Mostly I wanted to know: with this information in hand what actions can be taken that couldn't be taken previously or what existing actions become easier/faster/better?

As an example the migration status page enables people to see what blockers are and try to push them along one way or another.

This seems like a fine thing to have.

One thing to consider is if we should also issue issues into feedstocks who's version bumps fail, we'd need some controls around this (so we don't issue multiple issues and only issue them for chronic issues).

**Comment by beckermr** [comment]
My main goal is that the bot team should have some idea without having to dig in the CI logs. We should issue issues for failed migration PRs if we think we have found a valid upstream version. Unfortunately we are still finding a lot duds right now so it probably makes sense to only do this for well structured sources like pypi, GitHub, cran etc.
