### ISSUE TITLE
staged-recipes conversion down

### ISSUE THREAD

**Issue by beckermr** [conda-forge/status#80]
Recipe conversion on staged-recipes is currently down. We are working to fix it and hope to have it fixed in the next few hours.

**Comment by beckermr** [comment]
cc @isuruf @ocefpaf

**Comment by ocefpaf** [comment]
@isuruf let me know what you need me to do. I tried syncing Travis like we did in the past but that did not seem to have fixed it :-/

**Comment by isuruf** [comment]
This is fixed now.
