### ISSUE TITLE
Travis-CI ppc64le builds sometimes stall

### ISSUE THREAD

**Issue by xhochy** [conda-forge/status#81]
Builds randomly stall after some minutes and produce no output so that they are killed later by the 10min-no-output-timeout.

**Comment by xhochy** [comment]
See: 

 * https://travis-ci.com/github/conda-forge/arrow-cpp-feedstock/jobs/322157879
 * https://travis-ci.com/github/conda-forge/pandas-feedstock/jobs/320030540

**Comment by isuruf** [comment]
Seems to be fixed now

**Comment by xhochy** [comment]
Problem sadly persists: https://github.com/conda-forge/arrow-cpp-feedstock/runs/684238048

**Comment by xhochy** [comment]
Seems to be gone for a while again.
