### ISSUE TITLE
Webservices including rerendering down

### ISSUE THREAD

**Issue by carlodri** [conda-forge/status#86]
the bot doesn't seem to answer to rerender requests, see https://github.com/conda-forge/pyusid-feedstock/pull/14

**Comment by jakirkham** [comment]
Is this still an issue, @carlodri? Seems the re-rendering went through on that PR 🙂

**Comment by carlodri** [comment]
Hi @jakirkham! I just checked and it seems to me like the bot never replied. I'm giving it another chance.... :-)

**Comment by carlodri** [comment]
Looks like it's still not answering....

**Comment by jakirkham** [comment]
Does not appear to be an issue with the bot. The feedstock just had a PR that lacked all of the bits needed for the new re-rendering process. Should now be fixed.

**Comment by isuruf** [comment]
Rerendering was down due to not being able to create temporary directories. (Maybe TMP_MAX was hit). I restarted the webservice 3 days ago and it fixed the issue.
