### ISSUE TITLE
autotick bot is down

### ISSUE THREAD

**Issue by beckermr** [conda-forge/status#97]
The autotick bot is down for extended maintenance.

**Comment by h-vetinari** [comment]
Any update?

**Comment by beckermr** [comment]
Thanks for asking!

We completed the maintenance we wanted to do but ran into a hard technical issue on solver performance. We're shooting for midweek to have it back up, but we cannot promise anything.

**Comment by beckermr** [comment]
We have resolved the maintenance issues (finally!). Note that mamba solver checks have been turned off until we fix a bug where the solver appears to hang.
